### PR TITLE
Support dots in metadata

### PR DESCRIPTION
**Pull request by nadako**
also don't support $ in metadata, because I don't think Haxe does this

---

this is my first PR so I'm making it draft with the following questions to be resolved first:

- How to properly add test for this?
- I regenerated the file by clicking "Run JFlex Generator" on haxe.flex and the diff suggests some different version than was used before, I don't know if there are any consequences to that.

### CODE REVIEW

**Comment by EricBishton** [comment]
As far as Grammar-Kit goes, use the version that gradle downloads for you.  Newer versions cause the plugin to be IntelliJ-version-specific.  As far as JFlex goes, I haven't seen the upgrade message myself.

**Comment by nadako** [comment]
> As far as Grammar-Kit goes, use the version that gradle downloads for you. Newer versions cause the plugin to be IntelliJ-version-specific. As far as JFlex goes, I haven't seen the upgrade message myself.

What would be the exact gradle commands to download everything and re-generate `_HaxeLexer.java`? :) Sorry I'm really not familiar with this ecosystem.

**Comment by EricBishton** [comment]
For tests, you can get away with just adding your cases to ...\testData\parsing\haxe\declarations\class\FullOfMacro.hx, and then updating the Goldens in ...\testData\parsing\haxe\declarations\class\FullOfMacro.txt.  The specific test that runs those is ...\testSrc\com\intellij\plugins\haxe\lang\parser\declarations\ClassDeclarationTest.java

The easy way to update is to change the .hx file and run the test -- it will fail.  Then take a look at the failure diff (in IntelliJ).  After verifying that the new AST is what you expect, then use the "<<" buttons to copy the changes into the Goldens.  Run the test again to see it pass.

**Comment by EricBishton** [comment]
Also, you should be working from and posting to the 'develop' branch.

**Comment by EricBishton** [comment]
> What would be the exact gradle commands to download everything and re-generate _HaxeLexer.java? :) Sorry I'm really not familiar with this ecosystem.

https://github.com/HaxeFoundation/intellij-haxe/#build-command

"Note that the first time you build the project Gradle will download the requested version of IntelliJ Ultimate and any other other dependencies."

Also, see:
https://github.com/HaxeFoundation/intellij-haxe/blob/master/CONTRIBUTING.md#development-environment
https://github.com/HaxeFoundation/intellij-haxe/blob/master/CONTRIBUTING.md#building

**Comment by nadako** [comment]
Closing in favor of #961

**Pull request closed without merging**
