### PR TITLE
Fixed parser recovering for "extends" and "implements" statements.

### PR DESCRIPTION
**Pull request by mayakwd**
Closes issues #137

### CODE REVIEW

**Comment by EricBishton** [comment]
Ah, yes!  That is much better parsing rule.  particularly given that implementsList already deals with the `+`.

The question is: Is there any code relying on the old implementation allow a list of types inside of the extends/implements PsiElements?

**Comment by mayakwd** [comment]
I haven't found any issues with new rules

**Comment by EricBishton** [comment]
Did you make a code survey?

**Comment by EricBishton** [comment]
The refactoring code is using it:  You may want to test ExtractInterface, ExtractSuperclass, MemberPullUp, MemberPushDown.

**Comment by EricBishton** [comment]
And then there are the 150 usages of AbstractPsiElement.getExtendsList() in IDEA itself.  But, I'm pretty sure they expect the new structure (and were probably broken before).

**Comment by EricBishton** [comment]
I'll wait on this one until you (or I) have had a chance to try the refactoring.

**Comment by mayakwd** [comment]
Extract interface is already broken (without this pr), it's generating .java file with haxe code, with wrong content, and throwing exception.
Exceptions with extract superclass and pull up/pull down in current build (without pr) :-\
I'll create an issues and will fix it.

**Comment by mayakwd** [comment]
Other stuff works as expected

**Comment by EricBishton** [comment]
OK.  I'll pull this, then.

**Pull request merged**
