### PR TITLE
when doing syncProjectClasspath check if project SDK is Haxe SDK

### PR DESCRIPTION
**Pull request by as3boyan**

### CODE REVIEW

**Comment by EricBishton** [comment]
What problem does this fix?

**Comment by as3boyan** [comment]
We had #397 before, but it seems like there is no such error anymore if we create Java project

**Comment by EricBishton** [comment]
So, the purpose now is to ensure that the error doesn't appear with other types of projects, too?  (Which I think is fine.  I'm just trying to figure out whether you've decided that we don't need it after your last bit of testing.)

**Comment by as3boyan** [comment]
I think it attempts to get haxelib data for other types of projects

**Comment by EricBishton** [comment]
The Travis failure is only with the last 2016.3 version which isn't available from JetBrains' site.  I'm going to merge anyway.

**Comment by EricBishton** [comment]
@as3boyan Can you please close any issues this fixed and any PRs that are now abandoned?  Thanks.

**Pull request merged**
