### PR TITLE
Disable SplitDeclarationAndAssignment for now (later can be enabled a…

### PR DESCRIPTION
**Pull request by as3boyan**
…gain, just implementation needs to be improved to take into account reported issues)

because of https://github.com/HaxeFoundation/intellij-haxe/issues/544

### CODE REVIEW

**Comment by as3boyan** [comment]
Tests fail because haxelib right now is not available

**Comment by EricBishton** [comment]
When I apply this change locally, I don't get any difference in behavior. What difference did you see, Boyan?

(Nice to hear from you, BTW.)

**Comment by EricBishton** [comment]
I just pushed a parser fix.  Check out PR #557.

**Comment by as3boyan** [comment]
Indeed it is a parser error, my bad. This PR does not helps to solve the issue.

**Pull request closed without merging**
