### PR TITLE
Fix Issue544

### PR DESCRIPTION
**Pull request by EricBishton**
Updates the parser to allow anonymous functions to be called immediately upon definition.

### CODE REVIEW

**Comment by EricBishton** [comment]
@as3boyan @eliasku -- Can one of you please review this?  The fix is simple.  Most of the changes are in the test.

**Comment by as3boyan** [comment]
Thank you very much for such a super quick fix. Nice to see that you still work on plugin and we have plugin working on latest version of IDE.

To get plugin to compile I downloaded
specified version of grammar 1.2, but then I have to generate haxe.bnf and hxml.bnf using file context menu, would it use currently installed version of grammar-kit or 1.2? I thought that ant script will generate something automatically if I got it right.

**Comment by EricBishton** [comment]
Are you using Windows, by chance?  (I don't remember your primary environment.)  Windows doesn't have wget so the grammar-kit 1.2 has to be downloaded by hand at the moment, and then the jars it contains have to end up in the intllij-haxe project root directory.  After that, ant will generate the files in the gen/ tree during each build (command line or IDE).  We don't check anything into gen/ any more.

**Comment by as3boyan** [comment]
Yes, I downloaded it manually, and I put it in the root directory of intellij-haxe project. I will try again. If I remove `gen` folder, then I got missing classes

http://i.imgur.com/M6z26Myl.png

http://i.imgur.com/C94V4qg.png

**Comment by EricBishton** [comment]
Missing classes means (as you figured out) that the generation process didn't run correctly.  I don't know why.  I don't usually build on Windows.  I'll have to try it out and fix it.  I'll file a new issue.

> Ant tasks, some are grey, that means that they are skipped, right?
I'm not sure what that means.  The only difference I can see is whether it can be assigned a shortcut -- and that's probably _because_ of the reason why it's grey, not _why_ it's grey in the first place.

BTW, the other day, Simn was musing whether this syntax should even be allowed.  It's NOT straightforward to read, understand, _or_ parse.

**Comment by EricBishton** [comment]
@as3boyan Do you approve this for pull?

**Comment by as3boyan** [comment]
Your solution might allow to use ArrayAccess on anonymous functions, but that is not important, I think.
Approved for merge.

**Comment by EricBishton** [comment]
You are right!  I'll split the rule and retest.

**Comment by as3boyan** [comment]
@EricBishton I think it is better to use `bind` function in this case to make code easier to read

**Comment by EricBishton** [comment]
@as3boyan - This is better.  OK to merge?

**Comment by eliasku** [comment]
@EBatTiVo looks good! apologize for delay

**Comment by as3boyan** [comment]
@EricBishton Yeah, very good)

**Pull request merged**
