### PR TITLE
Haxe Main Class file chooser implementation

### PR DESCRIPTION
**Pull request by as3boyan**
Haxe Main Class file chooser implementation

### CODE REVIEW

**Comment by as3boyan** [comment]
I didn't made a separate branch, so it depends on #391

**Comment by as3boyan** [comment]
TreeHaxeClassChooserDialog is based on Java version, I used a "HaxeComponentIndex" to provide search for classes, basically it filters only classes from all found components

**Comment by EBatTiVo** [comment]
Nice.

A couple of thoughts on this:

 - Should we inspect the class, looking for a valid main() function, and if we don't find one, put up a warning dialog?  I wouldn't want to stop the selection, but it seems prudent to warn the user.  On the other hand, the haxelib runtime will tell them when it can't find an entry point.

- The OpenFL tab on the settings dialog is broken and won't save any changes.  This is an old bug, but I suspect that you won't be able to test properly until that's fixed.

- Can we please have some unit tests?

**Comment by as3boyan** [comment]
>>Should we inspect the class, looking for a valid main() function, and if we don't find one, put up a warning dialog? I wouldn't want to stop the selection, but it seems prudent to warn the user. On the other hand, the haxelib runtime will tell them when it can't find an entry point.

Great idea

>>The OpenFL tab on the settings dialog is broken and won't save any changes. This is an old bug, but I suspect that you won't be able to test properly until that's fixed.

I was wondering if it was fixed or not

>>Can we please have some unit tests?

Yeah, I need to understand how unit tests for forms are made, seen a few files made by Fedor

**Comment by EBatTiVo** [comment]
If you want to combine #391 with this PR, I will not mind.  In fact, I'd rather see that than dependent PRs.

**Comment by EricBishton** [comment]
Superseded by #583.

**Pull request closed without merging**
