### PR TITLE
hxcpp-debugger code generated using hxjava 3.2.0

### PR DESCRIPTION
**Pull request by m0rkeulv**
Generated hxcpp protocol code with hxjava 3.2.0 to get rid of warnings during plugin build and to get rid of messy class names with numbers and underscores.

### CODE REVIEW

**Comment by EricBishton** [comment]
This is a simple rebuild, right?

What do you think of creating a gradle task that generates this code and introducing the Haxe compiler to the tools necessary to create the plugin?  Then, we can just delete all of this code from the repo.

**Comment by m0rkeulv** [comment]
There is already one, but in its current state, it needs some paths updated to work properly. 

The problem with the current Gradle task and the reason why it is disabled is that it uses haxelib and changes hxjava and hxcpp-debugger to the versions needed to compile this project, but that may be different from what the user uses in other projects and may cause confusion and/or annoyance. 

It also require Haxe, which is yet another dependency that would need to be downloaded and installed by anyone who wants to build the project.

**Comment by EricBishton** [comment]
> The problem with the current Gradle task and the reason why it is disabled is that it uses haxelib and changes hxjava and hxcpp-debugger to the versions needed to compile this project, but that may be different from what the user uses in other projects and may cause confusion and/or annoyance.

There is an easy way around this:  Download the libraries to the tool directory and use them via `-cp` rather than `-lib`.  That way we aren't messing using haxelib at all.  The only caveat here is that we will also need to specify any `-Dxxx` defines that the library would do via haxelib.json.

> It also require Haxe, which is yet another dependency that would need to be downloaded and installed by anyone who wants to build the project.

The mid-term plan is to require Haxe anyway.  We want to start using Haxe sources for the plugin, particularly so that we can use the haxe-languageserver project (and get all of the vshaxe functionality).  We will also want to use a specific version of Haxe, rather than what the user has installed so that we can control the bugs that are introduced.  We will need to control the environment during our builds so that nothing from any user installation shows up.

(Also, something to think about is that we might be able to use gradle tasks from within the plugin -- at run time  -- to help install Haxe and haxelibs (particularly hxcpp-debugger) for the user.  I'm hoping we can eventually get to the ease-of-startup that HaxeDevelop has.)

**Comment by EricBishton** [comment]
Rather than continue to hold this up until we get the compiler included in the build, I'll just pull it for now. We can deal with generating these files during the build in another task.

**Pull request closed without merging**
