### PR TITLE
Support one-liner style for conditional-compilation

### PR DESCRIPTION
**Pull request by eliasku**
- Fix parsing of one-liner conditional complation style (issue #417, #121, partly #115).
- Std: StringTools and Co completion finally provided!
- Release Notes are udpated
- Test for parsing added

### CODE REVIEW

**Comment by SlavaRa** [comment]
Yeah :)

**Comment by EricBishton** [comment]
@eliasku I may delay taking this one because I'm  in the middle of a fix that will make this obsolete.

**Comment by eliasku** [comment]
@EricBishton Cool, let me look :)

**Comment by EricBishton** [comment]
@eliasku Let me make sure it compiles and I'll push it.

**Comment by EricBishton** [comment]
@eliasku See the "ConditionalCompilationParsingFixes" branch.  It's not all working yet, but you can see the shape it's taking.  (We can pick up a conversation on Slack.)

**Comment by EricBishton** [comment]
Since my changes are taking a while, I'm going to pull this anyway.

**Pull request merged**
