### PR TITLE
WIP: Add Flat Haxe Class File Icons to Match IntelliJ Look and Feel

### PR DESCRIPTION
**Pull request by CanIGetaPR**
I noticed the current class file icons look 3d while the rest of IntelliJ uses flat icons:

image

This feels to me like it clashes with the flat IntelliJ style, so I mashed together some flat icons using the IntelliJ IDEA base icons and putting a flatter haxe logo on top of them.

C_Logo_Flat
E_Logo_Flat
I_Logo_Flat
method-logo-flat

IntelliJ IDEA Flash/Flex plugin use a similar icon for actionscript class files:
image

I feel like I should add a white background around the haxe logo like IntelliJ have done it around the AS logo but I'll wait for feedback and the green light on this first.

### CODE REVIEW

**Comment by EricBishton** [comment]
If you don't mind doing the white outline thing, I think it would look great.  

If it's easy, maybe we can leave the old versions in the  builds intended for older versions of IDEA.  (I think 2019.3 was when they changed, but we can do the old versions for pre-2019 and newer versions for 2019+.)  We can either put all of the icons in the jar and switch them at run-time, or we can swap them at build time (which I think is actually harder.  What do you think?

**Comment by EricBishton** [comment]
@CanIGetaPR - Hit me up on email.  Let's get you onto Slack.

**Comment by CanIGetaPR** [comment]
> @CanIGetaPR - Hit me up on email. Let's get you onto Slack.

I switched from slack to discord, you wouldn't be on discord would you?

**Comment by EricBishton** [comment]
> you wouldn't be on discord would you?
> 
> @EricBishton

I'm on all of them.  For Discord: GreyBeard_hash_0905

**Comment by CanIGetaPR** [comment]
C_Logo_Flat

**Comment by EricBishton** [comment]
CanIGetaPR's current inkscape sources for these icons:
https://cdn.discordapp.com/attachments/761286369682784256/761756330733207572/New_IntelliJ_Haxe_Icons.zip

**Comment by demurgos** [comment]
Thank you very much for the  PR: these new icons fit way better with the newer IDEA versions.

An improvement would be to use transparency instead of opaque white for the outline: it would fit with both light and dark themes.

**Comment by demurgos** [comment]
I gave it stab by rewriting the whole icon by hand: I fixed the Haxe logo alignment and used a simplified version based of Haxe´s favicon. The code is way shorter:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
    <mask id="outline">
        <rect x="0" y="0" width="16" height="16" fill="white" />
        <rect x="9" y="9" width="7" height="7" fill="black" />
    </mask>
    <g fill="none" fill-rule="evenodd" mask="url(#outline)">
        <path fill="#40B6E0" fill-opacity=".6" d="M15,8 C15,11.866 11.866,15 8,15 C4.134,15 1,11.866 1,8 C1,4.134 4.134,1 8,1 C11.866,1 15,4.134 15,8"/>
        <path fill="#231F20" fill-opacity=".7" d="M5,4.28253174 C4.53,4.74153174 4.028,4.978 3.1,5 C2.061,5.022 1,4.2794 1,3.0004 C1,1.7124 1.971,1 3.1,1 C3.94833171,1 4.54833171,1.18475342 4.9,1.55426025 L5.5162,0.836730957 C4.8293999,0.270175195 4.28826904,0.0004 3.0982,0.0004 C1.3402,0.0004 0.0002,1.3584 0.0002,3.0004 C0.0002,4.6824 1.3642,6.0004 3.0022,6.0004 C4.29284668,6.0004 5.0232,5.5934 5.6162,4.9814 C5.2054,4.51548783 5,4.28253174 5,4.28253174 Z" transform="translate(5 5)"/>
    </g>
    <g>
        <rect x="11" y="11" width="4" height="4" fill="#f7941e" />
        <path d="M11,13 l-1,-1.6 l0,-1.4 l1.4,0 l1.6,1 Z" fill="#fdb813" />
        <path d="M11,13 l-1,1.6 l0,1.4 l1.4,0 l1.6,-1 Z" fill="#fdb813" />
        <path d="M15,13 l1,-1.6 l0,-1.4 l-1.4,0 l-1.6,1 Z" fill="#f58220" />
        <path d="M15,13 l1,1.6 l0,1.4 l-1.4,0 l-1.6,-1 Z" fill="#f58220" />
    </g>
</svg>
```

Rendered:

image

image

image

image

**Comment by CanIGetaPR** [comment]
> 
> 
> I gave it stab by rewriting the whole icon by hand: I fixed the Haxe logo alignment and used a simplified version based of Haxe´s favicon. The code is way shorter and should be less blured:
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
>     <mask id="outline">
>         <rect x="0" y="0" width="16" height="16" fill="white" />
>         <rect x="9" y="9" width="7" height="7" fill="black" />
>     </mask>
>     <g fill="none" fill-rule="evenodd" mask="url(#outline)">
>         <path fill="#40B6E0" fill-opacity=".6" d="M15,8 C15,11.866 11.866,15 8,15 C4.134,15 1,11.866 1,8 C1,4.134 4.134,1 8,1 C11.866,1 15,4.134 15,8"/>
>         <path fill="#231F20" fill-opacity=".7" d="M5,4.28253174 C4.53,4.74153174 4.028,4.978 3.1,5 C2.061,5.022 1,4.2794 1,3.0004 C1,1.7124 1.971,1 3.1,1 C3.94833171,1 4.54833171,1.18475342 4.9,1.55426025 L5.5162,0.836730957 C4.8293999,0.270175195 4.28826904,0.0004 3.0982,0.0004 C1.3402,0.0004 0.0002,1.3584 0.0002,3.0004 C0.0002,4.6824 1.3642,6.0004 3.0022,6.0004 C4.29284668,6.0004 5.0232,5.5934 5.6162,4.9814 C5.2054,4.51548783 5,4.28253174 5,4.28253174 Z" transform="translate(5 5)"/>
>     </g>
>     <g>
>         <rect x="11" y="11" width="4" height="4" fill="#f7941e" />
>         <path d="M11,13 l-1,-1.6 l0,-1.4 l1.4,0 l1.6,1 Z" fill="#fdb813" />
>         <path d="M11,13 l-1,1.6 l0,1.4 l1.4,0 l1.6,-1 Z" fill="#fdb813" />
>         <path d="M15,13 l1,-1.6 l0,-1.4 l-1.4,0 l-1.6,1 Z" fill="#f58220" />
>         <path d="M15,13 l1,1.6 l0,1.4 l-1.4,0 l-1.6,-1 Z" fill="#f58220" />
>     </g>
> </svg>
> ```
> 
> Rendered:
> 
> image
> 
> image
> 
> image
> 
> image

Thank you, I have no idea what I was doing with Inkscape.
Funnily enough in the meantime I took a look at your profile and contributed a PR to open flash, it looks like we each contributed something to each others' tasks. Thank you for your help! : ]

**Comment by demurgos** [comment]
Thank you. If it´s okay, may I open a new PR with my version of the icons? I can quickly apply the same transformation to all the icon types.

**Comment by EricBishton** [comment]
@CanIGetaPR So... now you're going to take @demurgos' idea and apply it to all of the icons?  What's the plan to get this finished?

**Comment by CanIGetaPR** [comment]
> 
> 
> Thank you. If it´s okay, may I open a new PR with my version of the icons? I can quickly apply the same transformation to all the icon types.

That would be best, thank you.

**Comment by EricBishton** [comment]
Oops.  Missed @demurgos last update.  A new PR is fine if it makes more sense.

**Comment by demurgos** [comment]
Okay, I´ll send it in a few minutes.

**Comment by EricBishton** [comment]
Superceded by #1084

**Pull request closed without merging**
