### PR TITLE
Compiler completion

### PR DESCRIPTION
**Pull request by EricBishton**
The feature is not yet complete, but it _is_ useful, and the code is just growing.  So, let's get this reviewed and in place before it grows too huge.

### CODE REVIEW

**Comment by EricBishton** [comment]
@eliasku - Can you or one of your guys take a look at this?  It's rather large, I'm sorry to say.  On the other hand, if folks just want to grab the code and test it, then that may be easier and more useful than visual inspection.  (This code is actually in the 0.10.1.Test.CompilerCompletion pre-release on the releases page.)  so far, I've only got one tester with any feedback.

**Comment by EricBishton** [comment]
I'm going to pull this in without review, because it's been sitting here for a while already and I need to do more work on it.  The feature is disabled by default anyway, so it should have little impact on those who are unaware.

**Comment by as3boyan** [comment]
So you added a way to control completion from compiler? That should improve performance and remove stutters when used with OpenFL, that should enhance coding experience.

**Comment by EricBishton** [comment]
The biggest thing that lead to elimination of stutters was changing how the subprocess was launched and not waiting for it to finish/return before checking whether the process should be canceled as a result of a keypress.  Now, there is a parallel polling loop that checks for ProcessCanceled that will kill the compiler process.

Turning off compiler completion via the UI was more about being able to commit the new changes and test the feature without affecting all users.

**Comment by as3boyan** [comment]
Good work, that is major improvement

**Pull request merged**
