### PR TITLE
Compiler completion

### PR DESCRIPTION
**Pull request by EricBishton**
Fix completion when using OpenFL.
Compiler completions now match the PSI completion output.
Updated the icons to use Haxe logos.

### CODE REVIEW

**Comment by EricBishton** [comment]
Was reviewed by @EliasKu.

**Comment by cmandlbaur** [comment]
Is this only useful for use with OpenFL?

**Comment by cmandlbaur** [comment]
Just built the plugin and to answer my own question, this works for other libs too.

Awesome to see code completion on macros! 

One comment on the iconss though is that their backgrounds aren't transparent. FYI The icon that the material theme plugin has for Haxe is really slick looking.

**Comment by EricBishton** [comment]
The Haxe logos are intentionally placed on black backgrounds, just like (most of) the logos on the haxe web site.  The portions of the icons that are not Haxe logos still have transparent backgrounds.

**Pull request merged**
